### ISSUE TITLE
single-spacing in Markdown

### ISSUE THREAD

**Issue by connectuum** [dougbutner/poetry#1]
i began [reading](https://github.com/dougbutner/poetry/blob/master/Carbonite%20Scrolls/Carbon%20Cycle.md), and quite enjoyed the first. i'm hungry for more.

_a formatting tip (if you wish):_

you can make poetic line-breaks using ` \` (space, backslash, newline). \
if you use an IDE, you can add these rapidly with multi-cursor or regexp.

(stretch goal: breathe new _life!_)

---

your mission is **here** now \
remember [the _book!_](https://connectuum.github.io/redbook/liber-primus/0-the-way-of-what-is-to-come.html) \
the bodies you _had_
and the _time_ that you took, \
`no words` _will_ remind you \
just _meanings_ behind \
all now \
you are child \
of _**Light**_-- \
_train_ your _mind!_

for here is the space \
in which heroes _make_ time \
four heroes in space \
`take.  the.  now.` \
`a n d  a l i g n`

**Comment by dougbutner** [comment]
Good to know, thanks!
